// Centralized styles for project components
export const STYLES = {
  container: {
    minHeight: "100vh",
    padding: "0",
  },
  headerRow: {
    padding: "24px 0",
  },
  headerCol: {
    paddingLeft: "60px",
    paddingRight: "30px",
  },
  headerTitle: {
    fontSize: "28px",
    fontWeight: "700" as const,
    marginBottom: "4px",
    color: "#1a1a1a",
    lineHeight: "1.2",
  },
  headerSubtitle: {
    fontSize: "14px",
    color: "#666666",
    lineHeight: "1.4",
    marginBottom: "0",
  },
  buttonCol: {
    display: "flex" as const,
    justifyContent: "flex-end" as const,
    paddingRight: "60px",
  },
  primaryButton: {
    backgroundColor: "#28a745",
    color: "#fff",
    border: "none",
    borderRadius: "6px",
    padding: "10px 24px",
    fontSize: "14px",
    fontWeight: "600" as const,
    cursor: "pointer",
    transition: "background-color 0.3s ease",
    boxShadow: "0 2px 8px rgba(40, 167, 69, 0.2)",
  },
  primaryButtonHover: "#218838",
  spacer: { padding: "10px 0px" },
  statCard: {
    borderRadius: "15px",
    boxShadow: "0 4px 9px rgba(0, 0, 0, 0.1)",
  },
  statCardBody: { padding: "20px" },
  searchInputWrapper: { position: "relative" as const },
  searchIcon: {
    position: "absolute" as const,
    left: "16px",
    top: "50%",
    transform: "translateY(-50%)",
    color: "#6c757d",
    pointerEvents: "none" as const,
  },
  searchInput: {
    borderRadius: "8px",
    border: "1px solid rgb(179, 179, 179)",
    padding: "12px 16px 12px 40px",
    fontSize: "14px",
    backgroundColor: "white",
    height: "48px",
  },
  dropdown: { height: "100%" },
  dropdownButton: {
    backgroundColor: "white",
    border: "1px solid rgb(179, 179, 179)",
    borderRadius: "8px",
    padding: "12px 16px",
    color: "#212529",
    height: "48px",
  },
  projectsContainer: {
    paddingLeft: "40px",
    paddingRight: "60px",
    paddingBottom: "60px",
  },
  projectCard: {
    marginBottom: "16px",
    borderRadius: "8px",
    border: "1px solid #e5e5e5",
    boxShadow: "0 2px 4px rgba(0, 0, 0, 0.05)",
  },
  projectCardBody: { padding: "20px" },
  projectHeader: {
    display: "flex" as const,
    justifyContent: "space-between" as const,
    alignItems: "flex-start" as const,
    marginBottom: "12px",
  },
  projectTitle: {
    margin: "0 0 8px 0",
    fontSize: "16px",
    fontWeight: "600" as const,
    color: "#1a1a1a",
  },
  projectDescription: {
    margin: "0",
    fontSize: "13px",
    color: "#666666",
  },
  projectDetails: {
    display: "grid" as const,
    gridTemplateColumns: "repeat(auto-fit, minmax(200px, 1fr))",
    gap: "16px",
    marginTop: "16px",
    paddingTop: "16px",
    borderTop: "1px solid #f0f0f0",
  },
  detailLabel: {
    margin: "0 0 4px 0",
    fontSize: "12px",
    fontWeight: "600" as const,
    color: "#666666",
  },
  detailValue: {
    margin: "0",
    fontSize: "14px",
    color: "#1a1a1a",
  },
  emptyState: {
    textAlign: "center" as const,
    padding: "60px 20px",
  },
  emptyStateImage: {
    maxWidth: "200px",
    marginBottom: "20px",
  },
  filterContainer: {
    paddingRight: "60px",
  },
} as const;
