name: Deploy to AWS

on:
  push:
    branches:
      - main

jobs:
  deploy-backend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Backend Environment
        run: |
          echo "PORT=${{ secrets.BACKEND_PORT }}" >> server/.env
          echo "JWT_SECRET=${{ secrets.JWT_SECRET }}" >> server/.env
          echo "JWT_EXPIRES_IN=${{ secrets.JWT_EXPIRES_IN }}" >> server/.env
          echo "JWT_COOKIE_EXPIRES_IN=${{ secrets.JWT_COOKIE_EXPIRES_IN }}" >> server/.env
          echo "NODE_ENV=${{ secrets.BACKEND_NODE_ENV }}" >> server/.env
          echo "EMAIL_FROM=${{ secrets.EMAIL_FROM }}" >> server/.env
          echo "EMAIL_HOST=${{ secrets.EMAIL_HOST }}" >> server/.env
          echo "EMAIL_USER=${{ secrets.EMAIL_USER }}" >> server/.env
          echo "EMAIL_PASS=${{ secrets.EMAIL_PASS }}" >> server/.env
          echo "EMAIL_PORT=${{ secrets.EMAIL_PORT }}" >> server/.env
          echo "AWS3_ACCESS_KEY=${{ secrets.AWS3_ACCESS_KEY }}" >> server/.env
          echo "AWS3_ACCESS_SECRET=${{ secrets.AWS3_ACCESS_SECRET }}" >> server/.env
          echo "REGION=${{ secrets.REGION }}" >> server/.env
          echo "BUCKET=${{ secrets.BUCKET }}" >> server/.env
          echo "DEV_DB_HOST=${{ secrets.DEV_DB_HOST }}" >> server/.env
          echo "DEV_DB_PORT=${{ secrets.DEV_DB_PORT }}" >> server/.env
          echo "DEV_DB_DATABASE=${{ secrets.DEV_DB_DATABASE }}" >> server/.env
          echo "DEV_DB_USER=${{ secrets.DEV_DB_USER }}" >> server/.env
          echo "DEV_DB_PASSWORD=${{ secrets.DEV_DB_PASSWORD }}" >> server/.env
          echo "PROD_DB_HOST=${{ secrets.PROD_DB_HOST }}" >> server/.env
          echo "PROD_DB_PORT=${{ secrets.PROD_DB_PORT }}" >> server/.env
          echo "PROD_DB_DATABASE=${{ secrets.PROD_DB_DATABASE }}" >> server/.env
          echo "PROD_DB_USER=${{ secrets.PROD_DB_USER }}" >> server/.env
          echo "PROD_DB_PASSWORD=${{ secrets.PROD_DB_PASSWORD }}" >> server/.env

      - name: Deploy Backend
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.BACKEND_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git pull origin main
            cd server
            npm install
            npm run build
            pm2 restart all

  deploy-frontend:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Setup Frontend Environment
        run: |
          echo "VITE_NODE_ENV=${{ secrets.FRONTEND_NODE_ENV }}" >> client/.env

      - name: Deploy Frontend
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.FRONTEND_HOST }}
          username: ${{ secrets.USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            git pull origin main
            cd client
            npm install
            npm run build
            sudo cp -r /home/ubuntu/client/dist/* /var/www/html/
